create table if not exists public.profiles (
  id bigint generated by default as identity primary key,
  name text not null,
  knowledge_base text not null,
  is_active boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists profiles_active_idx on public.profiles (is_active);

insert into public.profiles (name, knowledge_base, is_active)
values (
  'Default Profile',
  'Describe your offer, ideal customer, proof points, pricing, objections, and differentiators here.',
  true
)
on conflict do nothing;
